### ISSUE TITLE
Does not work with new Firefox (48+) browsers

### ISSUE THREAD

**Issue by kmorcinek** [cezarypiatek/Tellurium#21]
Now it does not work for SampleUITest for Firefox.

There is need to switch to geckodriver:

http://stackoverflow.com/questions/38916650/what-are-the-benefits-of-using-marionette-firefoxdriver-instead-of-the-old-selen/38917100#38917100

I have tried but had not luck, and my time run out.

@cezarypiatek btw which version of FF (x86, x64) are you using? There are different drivers and I think we should stick to the one that you have.

**Comment by cezarypiatek** [comment]
So far I've been using  drivers x86.  We have to migrate Tellurium to SeleniumHQ 3 in order to use gecko driver.

**Comment by cezarypiatek** [comment]
@kmorcinek Currently I'm unable to migrate Tellurium to Selenium 3.X because geckodriver has no option of taking full page screenshots. Problem is described in this issue https://github.com/mozilla/geckodriver/issues/570 Without full page screenshots VisualAssertions seems to be partially useless. You can still run tests on Firefox with Tellurium and Selenium 2.53, simply install firefox 47 and block auto-updates.  There is also an option for creating BrowserAdapter from existing driver so there is a chance that it could work with selenium 3.X (try install Tellurium, update Selenium to 3.X and  add appropriate binding redirect in app.config)

**Comment by cezarypiatek** [comment]
I was able to successfully migrate to Selenium 3.6 with support for legacy firefox 47.0.1 as well for the newest one with geckodriver.
